language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35,coverage,lint,unused_code,mypy
    - python: 3.6
      env: TOXENV=py36,coverage,lint,unused_code,mypy
install:
  - pip install tox
script:
  - tox